//==================================================
// This file contains the Excluded objects
// Generated By User: hanyuxin
// Format Version: 2
// Date: Sun Jul  5 23:08:51 2026
// ExclMode: default
//==================================================
CHECKSUM: "1452221095 4128477256"
INSTANCE: tb_picorv32.u_npu_wrapper
Fsm pf_state "3576936494"
Transition PF_AR->PF_IDLE "1->0"
Fsm pf_state "3576936494"
Transition PF_R->PF_IDLE "2->0"
Fsm state "1717470879"
Transition S_COMPUTE->S_IDLE "6->0"
Fsm state "1717470879"
Transition S_WAIT_ROW->S_IDLE "3->0"
Fsm state "1717470879"
Transition S_WAIT_FIFO->S_IDLE "5->0"
Fsm state "1717470879"
Transition S_WAIT_ALL_DONE->S_IDLE "8->0"
Fsm state "1717470879"
Transition S_UPDATE_WINDOW->S_IDLE "7->0"
Fsm state "1717470879"
Transition S_SHIFT_SYNC->S_IDLE "9->0"
Fsm state "1717470879"
Transition S_LOAD_WEIGHT->S_IDLE "2->0"
Fsm state "1717470879"
Transition S_LOAD_BIAS->S_IDLE "1->0"
Fsm state "1717470879"
Transition S_FIRST_LINE_INIT->S_IDLE "4->0"
Fsm wr_state "2702722393"
Transition 'h1->'h0 "1->0"
Fsm wr_state "2702722393"
Transition 'h3->'h0 "3->0"
Fsm wr_state "2702722393"
Transition 'h2->'h0 "2->0"
