# ==========================================
# PicoRV32 SoC 极简编译与仿真脚本 (多测试用例版)
# ==========================================

# 定义工具链
SRC_ROOT = ..
SRC_ROOT_NPU = $(SRC_ROOT)/npu_rtl
SIM_TOOL  = iverilog -g2012
SIM_RUN   = vvp
WAVE_TOOL = verdi

# ==========================================
# 核心优雅写法：动态文件列表选择
# 命令行用法: make CASE=1 或 make CASE=2 (默认走 1)
# ==========================================
CASE ?= 1

# [配置 1] PicoRV32 SoC 完整仿真 (默认)
SRC_FILES_1 = $(SRC_ROOT)/picorv32.v \
 			  $(SRC_ROOT_NPU)/pe.v \
              $(SRC_ROOT_NPU)/act_skew_buffer.v \
              $(SRC_ROOT_NPU)/sa_4_4.v \
			  $(SRC_ROOT_NPU)/npu_bottom_acc.v \
			  $(SRC_ROOT_NPU)/npu_ppu.v \
			  $(SRC_ROOT_NPU)/npu_deskew_buffer.v \
			  $(SRC_ROOT_NPU)/npu_sync_fifo.v \
			  $(SRC_ROOT_NPU)/npu_line_buffer.v \
              $(SRC_ROOT_NPU)/npu_axi_wrapper_lite.v \
			  $(SRC_ROOT_NPU)/axi_sram.v \
			  $(SRC_ROOT_NPU)/axil_interconnect.v \
			  $(SRC_ROOT_NPU)/arbiter.v \
			  $(SRC_ROOT_NPU)/priority_encoder.v \
			  $(SRC_ROOT_NPU)/axi_dp_sram_hybrid.v \
              $(SRC_ROOT_NPU)/tb_picorv32.v

# [配置 2] 裸核 NPU 子系统独立仿真
SRC_FILES_2 = $(SRC_ROOT_NPU)/pe.v \
              $(SRC_ROOT_NPU)/act_skew_buffer.v \
              $(SRC_ROOT_NPU)/sa_4_4.v \
			  $(SRC_ROOT_NPU)/npu_bottom_acc.v \
			  $(SRC_ROOT_NPU)/npu_ppu.v \
			  $(SRC_ROOT_NPU)/npu_deskew_buffer.v \
			  $(SRC_ROOT_NPU)/npu_line_buffer.v \
              $(SRC_ROOT_NPU)/tb_npu_core.v

# [配置 3] NPU & 虚拟CPU 系统级仿真
SRC_FILES_3 = $(SRC_ROOT_NPU)/pe.v \
              $(SRC_ROOT_NPU)/act_skew_buffer.v \
              $(SRC_ROOT_NPU)/sa_4_4.v \
			  $(SRC_ROOT_NPU)/npu_bottom_acc.v \
			  $(SRC_ROOT_NPU)/npu_ppu.v \
			  $(SRC_ROOT_NPU)/npu_deskew_buffer.v \
			  $(SRC_ROOT_NPU)/npu_line_buffer.v \
              $(SRC_ROOT_NPU)/npu_axi_wrapper_lite.v \
			  $(SRC_ROOT_NPU)/axi_sram.v \
			  $(SRC_ROOT_NPU)/axil_interconnect.v \
			  $(SRC_ROOT_NPU)/arbiter.v \
			  $(SRC_ROOT_NPU)/priority_encoder.v \
			  $(SRC_ROOT_NPU)/tb_npu_system.v

# [配置 4] 双端口Burst SRAM & 虚拟CPU 仿真
SRC_FILES_4 = $(SRC_ROOT_NPU)/axi_dp_sram_hybrid.v \
			  $(SRC_ROOT_NPU)/tb_axi_dp_sram_hybrid_burst.v

# 动态组装：根据 CASE 的值，把 SRC_FILES_1 或 SRC_FILES_2 赋值给 SRC_FILES
SRC_FILES = $(SRC_FILES_$(CASE))

# 防呆设计：如果选了不存在的 CASE (比如 make CASE=3)，直接报错终止
ifeq ($(strip $(SRC_FILES)),)
$(error "错误: 未知的仿真用例 CASE=$(CASE)！请指定 CASE=1 或 CASE=2 或 CASE=3")
endif

# ==========================================

# 定义生成的可执行文件和波形文件名称
TARGET    = sim.vvp
WAVE_FILE = $(WAVE_FILE_$(CASE))
WAVE_FILE_FSDB = $(WAVE_FILE_FSDB_$(CASE))

# [配置 1] PicoRV32 SoC 完整仿真 (默认)
WAVE_FILE_1 = picorv32_soc.vcd
WAVE_FILE_FSDB_1 = picorv32_soc.fsdb

# [配置 2] 裸核 NPU 子系统独立仿真
WAVE_FILE_2 = tb_npu_core.vcd
WAVE_FILE_FSDB_2 = tb_npu_core.fsdb

# [配置 3] 裸核 NPU 子系统独立仿真
WAVE_FILE_3 = tb_npu_system.vcd
WAVE_FILE_FSDB_3 = tb_npu_system.fsdb

# [配置 4] 双端口Burst SRAM & 虚拟CPU 仿真
WAVE_FILE_4 = tb_axi_dp_sram_hybrid_burst.vcd
WAVE_FILE_FSDB_4 = tb_axi_dp_sram_hybrid_burst.fsdb

# 默认目标：编译 -> 运行 -> 转化波形文件
all: compile run conv

# 1. 编译 Verilog 代码
compile:
	@echo "--- [1/4] Compiling Verilog Sources (CASE=$(CASE)) ---"
	$(SIM_TOOL) -o $(TARGET) $(SRC_FILES)

# 2. 运行仿真生成波形
run:
	@echo "--- [2/4] Running Simulation ---"
	$(SIM_RUN) $(TARGET)

# 3. 转换vcd为fsdb
conv:
	@echo "--- [3/4] Converting VCD to FSDB ---"
	vcd2fsdb $(WAVE_FILE) -o $(WAVE_FILE_FSDB)

# 4. 呼出 Verdi 查看波形 (后台运行，不阻塞终端)
wave:
	@echo "--- [4/4] Opening Waveform in Verdi ---"
	$(WAVE_TOOL) -ssf $(WAVE_FILE_FSDB) &

# 5. 开启检查代码并编译
check:
	@echo "--- [1/4] Compiling Verilog Sources (CASE=$(CASE)) ---"
	$(SIM_TOOL) -DSIM_CHECKS -o $(TARGET) $(SRC_FILES)

# 清理编译垃圾
clean:
	@echo "--- Cleaning Workspace ---"
	rm -f $(TARGET) $(WAVE_FILE) $(WAVE_FILE_FSDB)
